import Link from "next/link";
import { ArrowLeft, Users, Shield, Zap, History } from "lucide-react";

export default function CollabInfoPage() {
  return (
    <div className="min-h-screen bg-[#131314] text-slate-200 font-sans selection:bg-white/20">
      <div className="max-w-3xl mx-auto px-6 py-16 sm:py-24">
        <div className="mb-12">
          <Link href="/" className="inline-flex items-center text-sm font-medium text-slate-400 hover:text-white transition group mb-8">
            <ArrowLeft className="w-4 h-4 mr-2 group-hover:-translate-x-1 transition-transform" />
            Back to Home
          </Link>
          <h1 className="text-4xl sm:text-5xl font-medium text-transparent bg-clip-text bg-gradient-to-r from-slate-200 to-slate-400 mb-4 tracking-tight">
            How Collaboration Works
          </h1>
          <p className="text-lg text-[#c4c7c5]">
            Piechem AI allows you to invite peers, teachers, or students to collaborate on a single chat session in real-time.
          </p>
        </div>

        <div className="space-y-8">
          <div className="bg-[#1e1f20] border border-white/10 rounded-2xl p-6 sm:p-8">
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-xl bg-blue-500/20 text-blue-400 flex items-center justify-center shrink-0">
                <Users className="w-6 h-6" />
              </div>
              <div>
                <h3 className="text-xl font-medium text-white mb-2">Live Synchronization</h3>
                <p className="text-[#c4c7c5] leading-relaxed text-sm sm:text-base">
                  When you accept a collaboration request, the other user gains access to this specific chat. Any message they send, or any response generated by the AI, will instantly appear on your screen as well. It creates a unified learning space where both of you can ask questions together.
                </p>
              </div>
            </div>
          </div>

          <div className="bg-[#1e1f20] border border-white/10 rounded-2xl p-6 sm:p-8">
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-xl bg-green-500/20 text-green-400 flex items-center justify-center shrink-0">
                <Shield className="w-6 h-6" />
              </div>
              <div>
                <h3 className="text-xl font-medium text-white mb-2">Privacy & Control</h3>
                <p className="text-[#c4c7c5] leading-relaxed text-sm sm:text-base">
                  Collaborators only get access to the specific chat they requested. They cannot see your other chats, history, or profile details. As the owner of the chat, you remain in full control and can delete the chat at any time, which will remove it for all collaborators as well.
                </p>
              </div>
            </div>
          </div>

          <div className="bg-[#1e1f20] border border-white/10 rounded-2xl p-6 sm:p-8">
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-xl bg-amber-500/20 text-amber-400 flex items-center justify-center shrink-0">
                <Zap className="w-6 h-6" />
              </div>
              <div>
                <h3 className="text-xl font-medium text-white mb-2">Seamless Workflow</h3>
                <p className="text-[#c4c7c5] leading-relaxed text-sm sm:text-base">
                  To get started, simply click "Accept" on the request banner. The chat will immediately be unlocked for the requesting user. You can start sending messages immediately—you'll see their name next to their messages, distinguishing them from your own.
                </p>
              </div>
            </div>
          </div>

          <div className="bg-[#1e1f20] border border-amber-500/20 rounded-2xl p-6 sm:p-8 relative overflow-hidden">
            <div className="absolute top-0 left-0 w-1 h-full bg-amber-500"></div>
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-xl bg-amber-500/10 text-amber-500 flex items-center justify-center shrink-0">
                <History className="w-6 h-6" />
              </div>
              <div>
                <h3 className="text-xl font-medium text-white mb-2">Change Your Mind? Revert It.</h3>
                <p className="text-[#c4c7c5] leading-relaxed text-sm sm:text-base">
                  If the collaboration becomes too noisy or distracting, the chat owner has an exclusive <strong>"Back to where I was"</strong> option in the chat menu. Clicking this button instantly and permanently removes all third-party questions and their corresponding AI replies, flawlessly restoring the chat to your original, clean state.
                </p>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
